name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_website:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: install dependencies
        run: npm install
      
      - name: build app
        run: npm run build
      
      - name: create build zip file
        uses: actions/upload-pages-artifact@v3
        
  deploy:
    needs: build_website
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
